<?php

namespace Database\Seeders;

use App\Models\Booking;
use App\Models\Service;
use App\Models\Therapist;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    public function run(): void
    {
        $customers = User::where('role', 'customer')->get();
        if ($customers->isEmpty()) {
            return;
        }

        $services = Service::where('status', 'available')->get();
        if ($services->isEmpty()) {
            return;
        }

        $manager = User::where('role', 'manager')->first();
        $therapists = Therapist::where('status', 'active')->get();
        if ($therapists->isEmpty()) {
            return;
        }

        $bookingsData = [];

        // 1. Generate Historical Bookings (Past 30 days) to make analytics look good
        for ($i = -28; $i <= 0; $i++) {
            // Generate 1 to 4 bookings per day
            $bookingsToday = rand(1, 4);
            for ($b = 0; $b < $bookingsToday; $b++) {
                $status = rand(1, 100) <= 85 ? 'completed' : 'cancelled'; // 85% completion rate
                $bookingsData[] = [
                    'days_offset' => $i,
                    'start_time' => sprintf('%02d:00:00', rand(9, 18)), // 9am to 6pm
                    'service_idx' => rand(0, $services->count() - 1),
                    'status' => $status,
                    'payment_status' => $status === 'completed' ? 'paid' : 'cancelled',
                    'customer_idx' => rand(0, $customers->count() - 1),
                    'created_by_manager' => rand(0, 1) == 1,
                    'therapist_idx' => rand(0, $therapists->count() - 1),
                ];
            }
        }

        // 2. Generate Future Bookings
        for ($i = 1; $i <= 14; $i++) {
            $bookingsToday = rand(1, 3);
            for ($b = 0; $b < $bookingsToday; $b++) {
                $bookingsData[] = [
                    'days_offset' => $i,
                    'start_time' => sprintf('%02d:00:00', rand(9, 18)),
                    'service_idx' => rand(0, $services->count() - 1),
                    'status' => 'booked',
                    'payment_status' => 'paid',
                    'customer_idx' => rand(0, $customers->count() - 1),
                    'created_by_manager' => rand(0, 1) == 1,
                    'therapist_idx' => rand(0, $therapists->count() - 1),
                ];
            }
        }

        foreach ($bookingsData as $index => $data) {
            $customer = $customers[$data['customer_idx']] ?? $customers->first();
            $service = $services[$data['service_idx']] ?? $services->first();
            $therapist = $therapists[$data['therapist_idx']] ?? $therapists->first();
            
            $date = Carbon::today()->addDays($data['days_offset']);
            // If Sunday, shift to Monday to avoid "unavailable" Sunday constraints from other seeders
            if ($date->isSunday()) {
                $date->addDay();
            }

            $start = Carbon::parse($date->format('Y-m-d') . ' ' . $data['start_time']);
            $end = $start->copy()->addMinutes($service->duration_minutes);

            $ref = 'CPB-' . $date->format('Ymd') . '-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT);

            Booking::create([
                'booking_reference' => $ref,
                'customer_id' => $customer->id,
                'created_by_user_id' => $data['created_by_manager'] && $manager ? $manager->id : $customer->id,
                'service_id' => $service->id,
                'therapist_id' => $therapist->id,
                'appointment_date' => $date->format('Y-m-d'),
                'start_time' => $start->format('H:i:s'),
                'end_time' => $end->format('H:i:s'),
                'customer_name' => $customer->name,
                'customer_email' => $customer->email,
                'customer_phone' => '09123456789',
                'notes' => 'Generated by seeder.',
                'status' => $data['status'],
                'payment_method' => 'cash',
                'payment_status' => $data['payment_status'],
                'service_price' => $service->price,
                // Make a small random chance of discount applying to history so analytics looks good
                'discount_amount' => 0,
                'final_amount' => $service->price,
                'amount_paid' => $data['payment_status'] === 'paid' ? $service->price : 0,
                'notification_status' => 'email_sent',
                'created_at' => $date->copy()->subDays(rand(1, 3)),
                'updated_at' => $date->copy()->subDays(rand(1, 3)),
            ]);
        }
    }
}
